### ISSUE TITLE
Can't get dependencies reference for NestJS + TypeORM repositories

### ISSUE THREAD

**Issue by royhadad** [omermorad/automock#27]
The following is a working example using `jest-mock-extended`
![image](https://user-images.githubusercontent.com/39004075/211283499-30524445-2dd3-47d4-b146-2ab07918d759.png)

When using `automock`, this does not work.
![Screenshot 2023-01-09 at 12 06 39](https://user-images.githubusercontent.com/39004075/211283884-46dfb8b7-20f2-4b5c-8dbb-1786ed2c8cc1.png)

Type error:
```
TS2769: No overload matches this call.   Overload 1 of 2, '(type: string): Mocked<Repository<Workspace>>', gave the following error.     Argument of type 'string | Function' is not assignable to parameter of type 'string'.       Type 'Function' is not assignable to type 'string'.   Overload 2 of 2, '(type: Type<Repository<Workspace>>): Mocked<Repository<Workspace>>', gave the following error.     Argument of type 'string | Function' is not assignable to parameter of type 'Type<Repository<Workspace>>'.       Type 'string' is not assignable to type 'Type<Repository<Workspace>>'.
```

**root cause and potential fix:**
looking at the source code, the MockResolver class has an overloaded `get` method, 
1. `type: string` argument
2. `type: Type<TClass>` argument
![Screenshot 2023-01-09 at 12 12 14](https://user-images.githubusercontent.com/39004075/211284887-c12749d3-76af-49f6-bb72-20f3eba89560.png)

In the nestJS source code, there is no overload. just 1 method that accepts all of the types for the `type` argument.
![Screenshot 2023-01-09 at 12 14 54](https://user-images.githubusercontent.com/39004075/211285323-e923be85-63f4-4d6c-87e8-80565059bdb8.png)

Looking at the source code, it actually seems there is a 3rd overload with both arguments allowed.
for some reason it does not appear in the compiled version:
https://github.com/omermorad/automock/blob/1fbca1ea4dff58545dffea8f7b1aca9526f0d7f7/src/lib/mock-resolver.ts#L9

**Comment by omermorad** [comment]
Hi @royhadad, thank you for posting this issue.
Can you add a `string` casting? Tell me if it worked for you.

Anyways, the type you mentioned needs to be change, I will create an issue from this one.
